FSNotes.xcodeproj/project.pbxproj

Fixes source location of SourceCodePro ttf (previously the build phase attempted to copy this from the Downloads directory)
Don't code-sign for "Debug" builds. This allows other developers to build the app without having to remove code signing.

Minor fixes.

---

FSNotes/Base.lproj/Main.storyboard

I prefer this style — it also seems more in keeping with most recent apps. It might be the case that we need to switch to the previous style divider for vertical orientation though.

Make the split view divider thin.

---

FSNotes/Base.lproj/Main.storyboard

Suggested fix for issue #57.
Don't allow resizing of preferences window (this seems to be pretty standard in MacOS apps).

Disable resizing of preferences window

---

FSNotes/AppDelegate.swift
FSNotes/EditTextView.swift

Some of my notes have long titles, and as a fan of the vertical layout, there sometimes isn't room to view the entire title in the notes list. This PR puts the selected note's title into the App window title.

Set window title to selected note title

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/EditTextView.swift
FSNotes/Model/UserDefaultsManagement.swift
FSNotes/Preferences/PrefsViewController.swift

As per https://github.com/glushchenko/fsnotes/issues/63 this PR adds the ability to select the colours used for the note text and the note background.
There are a few issues, hopefully minor:
* I had to add two colour wells in the prefs for this, rather than using the existing ones provided by the `NSFontPanel`. Nothing I tried could get the colour info out of the `NSFontPanel` :(
* I couldn't turn off the colour wells inside the `NSFontPanel` — the commented code in my PR *does* remove them, but the method signature changed in 10.13, apparently, and thus won't work for earlier targets.
* I haven't applied the selected colours to the markdown preview. I am not sure if you'd want this (I don't use markdown myself). To achieve this, I guess you'd have to inject a line of CSS into the …

Allow note text and background color changes.

---

FSNotes/EditTextView.swift

See https://github.com/glushchenko/fsnotes/pull/87#issuecomment-356791250
This PR sets the text cursor to be white when on dark backgrounds.

Set cursor white when on dark-colored note backgrounds.

---

FSNotes/DateFormatter+.swift
FSNotes/Model/Note+CoreDataClass.swift

If a note is modified sometime today, display its date as a time eg "1:30 PM" instead of just the date.
As you can see I put the bulk of this into a little extension to `DateFormatter`. Solves https://github.com/glushchenko/fsnotes/issues/118.

Format dates as time only when date is sometime today.

---

FSNotes/EditTextView.swift
FSNotes/NotesTableView.swift
FSNotes/SearchTextField.swift
FSNotes/TextFormatter.swift
FSNotes/ViewController.swift

This PR removes the last bullet in a list if it was left empty. In other words, if you press enter after an auto-created bullet without entering any bullet text, the bullet is removed. This seems common behaviour in other apps.
I've also included em-dash and asterisk in the list of acceptable bullet characters.
Finally, I replaced a bunch of hard-coded hex and int values with named constants. Hope this is OK — I found the hard-coded values pretty hard to interpret. In fact, there's still at least one that I haven't been able to identify (`393475`), and there are numerous more that could be replaced throughout, but I didn't want to go too far right now.

Cancel auto bullets

---

FSNotes/Extensions/NSView+.swift
FSNotes/ViewController.swift

In recent versions, the background colour preference does nothing.
Back in 1.5.2 an extension to NSView was introduced which added a computed property called `backgroundColor`. Unfortunately this overwrote the property with the same name that is provided by NSTextView, thereby breaking the code which changes the background colour according to the preference setting. This PR fixes that by removing the naming conflict.

Reinstate changeable notes area background colour.

---

.gitattributes
.swiftlint.yml
FSNotes iOS/AppDelegate.swift
FSNotes iOS/EditorViewController.swift
FSNotes iOS/Extensions/UIFont+.swift
FSNotes.xcodeproj/project.pbxproj
FSNotes/AppDelegate.swift
FSNotes/Business/Note.swift
FSNotes/Helpers/FileSystemEventManager.swift
FSNotes/Helpers/ImagesProcessor.swift
FSNotes/View/NotesTableView.swift
FSNotes/View/SearchTextField.swift
FSNotes/View/SidebarProjectView.swift
FSNotes/ViewController.swift
FSNotesCore/Core iOS/FSNotesCore_iOS.h
FSNotesCore/Core iOS/Info.plist
FSNotesCore/Core macOS/Extensions/NSView+.swift
FSNotesCore/Core macOS/FSNotesCore_macOS.h
FSNotesCore/Core macOS/Helpers/UserDataService.swift
FSNotesCore/Core macOS/Info.plist
FSNotesCore/Shared/Extensions/DateFormatter+.swift
FSNotesCore/Shared/Extensions/String+.swift
FSNotesCore/Shared/Extensions/URL+.swift
FSNotesCoreTests/SharedTests/Extensions/DateFormatter+Tests.swift
FSNotesCoreTests/SharedTests/Extensions/String+Tests.swift
FSNotesCoreTests/iOSTests/FSNotesCore_iOSTests.swift
FSNotesCoreTests/iOSTests/Info.plist
FSNotesCoreTests/macOSTests/Helpers/UserDataServiceTests.swift
FSNotesCoreTests/macOSTests/Info.plist
Podfile

There appears to be a lot of code that is shared between the Mac and iOS apps, however it is littered with conditional compilation and appears to be prone to leaky abstractions. This is my stab at moving shared code out into frameworks that are embedded into their respective applications.
During this process I'm adding as many tests unit tests as I can because I see there aren't any tests in this project yet.

WIP: Extract core code into framework

---

FSNotes/Business/Note.swift
FSNotes/ViewController.swift

Fixed a bug where sometime the pin/unpin operation would not have disjoint sets of target cells
which caused some notes to be effectively hidden in the note list.
Closes #293

Fix: Allow arbitrary note pinning and unpinning.

---

FSNotes/AppDelegate+URLRoutes.swift

As per https://github.com/glushchenko/fsnotes/issues/160#issuecomment-408608966, convert `fsnotes://find/x%20y%20z` to search rather than look only for matching note titles.

Convert URL find to actually find :)

---

FSNotes/ViewController.swift

#389 
1. If preview mode is on
1.1. a user activates (clicks?) CMD+F
1.2. the app switches to edit mode
1.3. text find panel becomes visible
2. If edit mode is on and text find bar is visible
2.1. the app switches to preview mode
2.2. text find bar becomes hidden

Disable text find bar while in preview mode

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/ViewController.swift

Some improvements in renaming behavior. 
Now after `CMD+R` the title text field becomes editable and active.
But in case if you choose `Rename` from note cell's menu its title will become editable (as it was before)
https://duaw26jehqd4r.cloudfront.net/items/2E2K0K2V1G1z3j2N1D0q/Screen%20Shot%202018-10-25%20at%2011.09.57.png?v=10f49872)
https://duaw26jehqd4r.cloudfront.net/items/1U1J0S290d1N262G1S3M/Screen%20Shot%202018-10-25%20at%2011.11.48.png?v=53f5f9e8)

Move renaming field to title in editor view

---

FSNotes/Base.lproj/Main.storyboard

fixed scrollbar's top inset in the sidebar pane

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/View/EditTextView.swift

There was an issue when after switching to preview more the tiny black bar was appearing.
Before:
[link to gif (for some reason it doesn't want to load as an image)](https://media.giphy.com/media/jataoZJtY0lGHIwNJK/giphy.gif)
After:

fixed a scrolling issue in preview mode

---

FSNotes/Base.lproj/Main.storyboard

an issue appeared after my last resolving conflicts in the storyboard. And as the result, the title was disappearing when you switch to renaming mode. So I fixed layout constraints for the title label and set its line break to `Truncate Tail` instead of `Word Wrap`
https://duaw26jehqd4r.cloudfront.net/items/153H0F2x2A1l271y3035/Screen%20Shot%202018-10-29%20at%2001.21.17.png?v=7a4dd3e9)
https://duaw26jehqd4r.cloudfront.net/items/1q2a003E3c270Q1A2L3V/Screen%20Shot%202018-10-29%20at%2001.28.00.png?v=63be358d)

fix layout constraints for the title label

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/ViewController.swift

Added a click gesture recognizer to the title label. So now it can be switched to edit mode just by double-clicking on it.
For reviewers:
The change in the storyboard is just moving the title label above the hidable title bar view.

Switch title to edit mode by double-clicking on it

---

FSNotes/ko.lproj/Main.strings

I've found one mistake in Korean translation and fixed it.
Fixed:
- Korean translation: container type - None

Fix Korean translation: container type - None

---

FSNotes iOS/EditorViewController.swift
FSNotes iOS/View/NotesTableView.swift
FSNotes.xcodeproj/project.pbxproj
FSNotes/Business/Markdown.swift
FSNotes/MPreviewView.swift
FSNotes/View/EditTextView.swift
FSNotes/View/MarkdownView.swift
FSNotes/ViewController+Print.swift
FSNotes/ViewController.swift
Podfile

PR for #703
Module added:
- libcmark_gfm
Module removed:
- cmark-gfm-swift
- Down (conflict with libcmark_gfm, it seems not used)
New features:
- Footnotes (still need to fix, it opens external editor)
- Braket links with white spaces (ex. [Hello world](<Hello world.md>)
Note:
- Add additional file `FSNotes/Business/Markdown.swift`.
It contains single function which renders markdown as HTML.
- Add an  option `CMARK_OPT_FOOTNOTES` to `cmark_parser_new`
for footnotes.

Use libcmark_gfm rather than cmark-gfm-swift

---

Resources/Initial/FSNotes - Shortcuts.md
Resources/Welcome.bundle/1.textbundle/text.markdown
Resources/Welcome.bundle/2.textbundle/text.markdown
Resources/Welcome.bundle/4.textbundle/text.markdown
Resources/Welcome.bundle/5.textbundle/text.markdown
Resources/Welcome.bundle/6.textbundle/text.markdown
Resources/Welcome.bundle/7.textbundle/text.markdown

Hi!
I just found FSNotes and love it so far. As I was going through the welcoming flow (which is fantastic by the way), I found a few things that might be tweaked.
Many of these are small grammar and typographic changes.
One keyboard shortcut I found difficult was the Preview Mode. Technically it's command + ` since the ~ is achieved by shift + `. 
Trying to add clarity, I escaped the tick (`) character using this trick: https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown.
P.s. The `FSNotes - README.md` file includes a link to `[[Shortcuts]]` but this is not included in the bundle for iOS.

Update intro files

---

FSNotes/MPreviewView.swift
FSNotes/View/EditTextView.swift
FSNotes/View/EditorSplitView.swift
FSNotes/ViewController.swift

There were a few issues while resizing the master view in preview mode.
Before:
After:
I removed `splitViewDidResizeSubviews` from ViewController as it did not detect resizing by dragging splitView divider but only resizing the whole window size. But I added `splitViewDidResizeSubviews` to `EditorSplitView.swift` so now it handles resizing no matter how you resize the views. This also fixes the resizing issue while switching to fullscreen in preview mode.
Added check to stop loading note if it is the same as the current note. It was made to optimize performance.

Fixed resizing master view issue in Preview mode

---

FSNotesCore/Shared/Business/Git.swift

This fixes the crash described in #710
There was a crash in case if you right-click on a note in the note list. It was because the git binary is placed in `FSNotes.app/Contents/Resources/git` but not in `FSNotes.app/Contents/MacOS/git`.
Also replaced deprecated `process.launch()` with the new `process.run()` method

Fix #710: Git crash

---

FSNotes/ViewController.swift

The preview button has wrong state after app launch.
Steps to reproduce:
1. Open the app and turn preview mode on. At this moment the preview button is turned on.
2. Relaunch the app
3. Verify the preview button
Actual result:
Notes are in preview mode but the button is turned **off**
Expected result:
Notes are in preview mode but the button is turned **on**

Set proper preview button state after app launch

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/View/TitleTextField.swift
FSNotes/ViewController.swift

• I made title look less distractive.
• The buttons view (action view?) now appears/disappears with animation by changing its alpha but not hiding the view.
• The action view now won't appear while title is being editing.
• Changed title editing behaviour: it was needed to click twice on it for the first time but then it was switching to edit mode by just one click. Now it always two clicks.

Fix an issue when title covers lock and preview buttons after being edited

---

FSNotes/View/TitleTextField.swift
FSNotes/ViewController.swift

Steps to reproduce:
1. Open a note
2. Press `CMD+R` and change the title
3. Hover mouse cursor over the action buttons view
Expected result:
Action buttons become visible
Actual result:
Action buttons stay hidden

Fixed an issue when action buttons stop appearing after changing document's title

---

FSNotes/View/SidebarProjectView.swift

The fix for #811 
The issue was in detecting tag selection. Searching tag by index in array of sidebar items doesn't work because nested tags are not in this array.

Fix nested tags selection

---

Resources/Welcome.bundle/7.textbundle/text.markdown

Currently the \(ax^2 + bx + c = 0\) doesn't render because Markdown escapes backslashes.

Escape backslashes in MathJax example

---

FSNotes iOS/ViewController.swift
FSNotes/ViewController.swift

Fixes #793. 
The Todo section on the sidebar currently shows items with Todos regardless of whether all of the Todos are complete or not. This filters it so that once all of the Todos are checked, it will no longer show in the list.
I'd propose that there be a "Done" section on the sidebar if it is useful to show what todos have been finished off (I don't know that that would be useful myself). For now I've left it as is.
Notice how the Todo note is no longer visible in the gif after completing both todo items. It can of course show up in other sections, and it will show back up in the Todo section if you uncheck one of those checkboxes or add a new unchecked one.

Only show incomplete todos in the Todo section #793

---

FSNotes/fr.lproj/Main.strings

I tried to keep the labels as short as possible, but it's difficult not to lose context...
As for the "extra spaces", these are part of the French language. [Feel free to learn more](https://wiki.openoffice.org/wiki/Non_Breaking_Spaces_Before_Punctuation_In_French_(espaces_insécables)).
> In French language, some punctuation signs like ; : ! ? need to have a (non breaking) space between them and the word placed before them.

Fixes length issues with Fr translation (2)

---

FSNotes/Helpers/UserDefaultsManagement.swift

Addresses item 1 on #887
---
---

Improve default line spacing

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/Helpers/UserDefaultsManagement.swift
FSNotes/Preferences/PreferencesGeneralViewController.swift
FSNotes/ViewController.swift

I use a Mac with Touch Bar and tap accidentally on the ESC throws me to an empty view and focus on Search field, and this was driving me crazy as this happens in the middle of a heavy writing session, usually taking instant notes on a meeting.
PS: plus a little change on a subtle animation on titleBar, cosmetic and for design pleasure 💅🙂

Reset to search focus as an option

---

FSNotes/Business/Note.swift
FSNotes/Helpers/NotesTextProcessor.swift

With this change FSNotes is using a single annotated regex which covers a few
more bases like closing brackets, question marks, and apostrophes.
This allowed simplification of some tag-related sanity checks.
I also added checks to avoid highlighting number-only tags.
Before:
After:

Standardize tag matching on a single regex

---

FSNotes/Helpers/TextFormatter.swift

To reproduce the bug on master, put three spaces in front of a line and press `cmd + [` to untab. Nothing should happen, but the cursor moves to prev line.
Fixed by replacing `"   "` with `"    "`. Assuming it was a typo

Bugfix: In func def `unTab`, check for 4 spaces instead of 3

---

FSNotes iOS/Main.storyboard
FSNotes iOS/ViewController.swift

Fixes:
1. Adds truncation behaviour for long folder names.
Steps to reproduce:
a. Add a very long name for folder
b. Folder name is not truncating
2. Updates side bar width to appropriate size on first launch.
Steps to reproduce:
a. Open fsNotes (make sure side bar is closed and atleast one folder has a long name)
b. Open side bar
c. Tap on folder which has long name (can tap on any folder)
d. Side bar wil adjust after you tap: Issue*
https://github.com/glushchenko/fsnotes/assets/32197474/985b7699-21e6-4b4e-adff-e38fb7007058

Side bar bug fixes

---

FSNotes iOS/View/SidebarTableView.swift

https://github.com/glushchenko/fsnotes/issues/1530
The glitch appears because on folder selection we reload tags list [here](https://github.com/glushchenko/fsnotes/blob/d5e37c2fb2f1d840fe56c5e85666eb84db6178c2/FSNotes%20iOS/View/SidebarTableView.swift#L140)
Added check if a user taps on the selected folder, if yes don't reload notes. 
(On the screencast I tap on the selected folder and glitch doesn't appear)
The changes also fix another glitch when a user taps on the current project, notes list blinks

Fix of UI Glitch on iOS #1530

---

FSNotes Info (Notarized).plist
FSNotes/Info.plist

Simple typo fix.  Currently the typo appears in Finder under the "Kind" heading like so:

Fix "markdwon" typo in Info plist

---

FSNotes iOS/ViewController.swift
FSNotes/Business/Storage.swift

Fixes #1812.
The problem here was that `ViewController.loadDB()` can take quite a lot of time on the first run. At the same time, the `didBecomeActive()` iOS event was called, which scheduled a git pull task on a thread. This made the `checkNotesCacheDiff()` claim that no notes are known to the app yet, while those same notes were being loaded from the local file system.
This even lead to crashes every now and again due to thread safety issues with reference counting. Making sure that the git queue isn't interrupting the initial load fixes the problem entirely.

iOS: Suspend the Git queue until all notes are initially loaded

---

FSNotes iOS/View/NotesTableView.swift

When the user presses the "Git Add/commit/push" action and there are no changes to commit, currently a scary "GitError 12" modal shows.
With this change, the modal says what is actually happening: no changes to commit.

iOS: Do not treat "no changes" as a Git error when the user syncs

---

FSNotes/View/MPreviewView.swift

Do not use dark mode when building print preview

---

Resources/MPreview.bundle/index.html

Table font colours are the too dark in dark mode, therefore readability is lower than it should be. This minor change raises the readability of items that are drawn inside table in dark mode. There should be no impact in light mode.
Before:
After:

Alter table font colour contrast in dark mode
