FSNotes/ViewController.swift

Make note search case-insensitive.

Make search case-insensitive.

---

FSNotes/NoteCellView.swift

When a note cell is selected, change all the cell's text to white

Fix selected note cell text colors.

---

FSNotes/Model/Note.swift
FSNotes/NotesTableView.swift

Show alert before deleting; move deleted notes to the trash.
https://github.com/glushchenko/fsnotes/issues/14

Improve note deletion.

---

FSNotes/AppDelegate.swift
FSNotes/Base.lproj/Main.storyboard
FSNotes/EditTextView.swift
FSNotes/Model/UserDefaultsManagement.swift
FSNotes/PrefsViewController.swift
FSNotes/PrefsWindowController.swift
FSNotes/ViewController.swift

Improve font and font size selection.

---

FSNotes.xcodeproj/project.pbxproj
FSNotes/Utils/String+.swift
FSNotes/ViewController.swift

Improve search leniency as per https://github.com/glushchenko/fsnotes/issues/27

Search notes for search terms in any order.

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/MainWindowController.swift
FSNotes/Model/UserDefaultsManagement.swift
FSNotes/PrefsViewController.swift

I prefer to keep my notes visible even when i switch to another application. This PR adds that as a preference.

Add preference to hideOnDeactivate.

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/Model/UserDefaultsManagement.swift
FSNotes/PrefsViewController.swift
FSNotes/ViewController.swift

I like a bit of whitespace in my notes listing, but I can imagine others may not. I've added this as a user preference.

Add preference setting for cell spacing

---

FSNotes/Base.lproj/Main.storyboard
FSNotes/EditTextView.swift
FSNotes/Model/UserDefaultsManagement.swift
FSNotes/Preferences/PrefsViewController.swift

Closes https://github.com/glushchenko/fsnotes/issues/152

Auto-close brackets

---

FSNotes/AppDelegate+URLRoutes.swift
FSNotes/AppDelegate.swift

Also move app URL scheme code into separate file for clarity.
With this code, the app now responds to:
* `FSNotes://find/test%20note`
* `FSNotes://new/My%20New%20Note/Note%20body%20here.`

Add /new/note-name/encoded-note-contents route handler.

---

FSNotes.xcodeproj/project.pbxproj
Podfile

Because using the latest version of dependencies is good!
Changes
- Pinned dependencies that had no version specified to prevent future headaches
- Upgraded git dependencies since the published versions are now support swift 4
- Minor refactor of `podfile`

Upgrade dependencies

---

FSNotesCore/Core iOS/Extensions/NSTextStorage+.swift
FSNotesCore/Core macOS/Extensions/NSTextStorage+.swift

Fix compile issues

---

FSNotes/Business/Storage.swift

See https://github.com/glushchenko/fsnotes/issues/341

Omit packages from sidebar directory lists.

---

FSNotes/ViewController.swift

fix for #387
also added a few guards to prevent crashes while force unwrapping

fix a crash which happens when there is no row with such index

---

FSNotes/ViewController.swift

#393 Fixed an issue when the current filter resets after `Sort by` action

---

FSNotes/View/EditTextView.swift

fix for #395 Title doesn't change while in preview mode

---

FSNotes/Business/Note.swift
FSNotes/Helpers/NotesTextProcessor.swift

Convert app links to markdown links for preview mode

---

FSNotes/AppDelegate.swift
FSNotes/ViewController.swift

Fixed an issue when appearance may set with some delay while the app is starting

---

FSNotes iOS Share/NotesListController.swift
FSNotes iOS Share/ProjectListController.swift
FSNotes iOS/CloudDriveManager.swift
FSNotes iOS/EditorViewController.swift
FSNotes iOS/Extensions/ImageAttachment+.swift
FSNotes iOS/ViewController.swift
FSNotes/Extensions/ImageAttachment+.swift
FSNotes/Helpers/FileSystemEventManager.swift
FSNotes/View/NoteCellView.swift
FSNotes/View/NotesTableView.swift
FSNotes/ViewController.swift

This PR removes a few potential retain cycle culprits. Unfortunately there are still several leaks but tracking them can be quite time consuming.

Remove some potential retain cycles.

---

es.lproj/Localizable.strings

* plus some brand new translations

Fixed typo on line 17

---

Resources/Welcome.bundle/1.textbundle/text.markdown
Resources/Welcome.bundle/2.textbundle/text.markdown
Resources/Welcome.bundle/3.textbundle/text.markdown
Resources/Welcome.bundle/5.textbundle/text.markdown
Resources/Welcome.bundle/6.textbundle/text.markdown
Resources/Welcome.bundle/8.textbundle/text.markdown
Resources/Welcome.bundle/9.textbundle/text.markdown

Some grammatical errors and typos corrected. At places,  text was rewritten to be more fluid.

Smaller rewrites in initial textbundle files.

---

FSNotes/MPreviewView.swift
Resources/DownView.bundle/index.html

Fixed the copy code block button.
This may be as an alternate fix for issue #777

Fixed Copy code button

---

FSNotesCore/Shared/Business/Git.swift

Git path in the release version is different from when build the app in Xcode.
For some reason it compares with an old version of the Git.swift file.

Git path in the release version is different

---

FSNotes.xcodeproj/project.pbxproj
FSNotes/Business/LanguageType.swift
FSNotes/Preferences/PreferencesAdvancedViewController.swift
FSNotes/fr.lproj/Main.strings
fr.lproj/Localizable.strings

Ref to #582 
Since I am not a Swift developer at all, I can't be sure I did everything to ensure these translations are working properly.
I would recommend testing 🙂

French translation

---

FSNotes/fr.lproj/Main.strings
fr.lproj/Localizable.strings

Following #848
I trimmed the UI labels that were too long. Also fixed some other where the meaning was wrong. Plus some other typos.

Fixes length issues with Fr translation + typos

---

index.html

Makes the landing page copy consistent with the README. I also moved the feature list to the top of the page because IMO it's the most important thing for potential users to see.

Landing page copy edits

---

FSNotes/Helpers/UserDefaultsManagement.swift

Improve default line width

---

FSNotes/View/SidebarOutlineView.swift

finish: open subtag link in note on mac

---

FSNotes iOS Share/ja.lproj/Localizable.strings
FSNotes iOS/ja.lproj/InfoPlist.strings
FSNotes iOS/ja.lproj/Localizable.strings
FSNotes.xcodeproj/project.pbxproj
FSNotes.xcodeproj/xcshareddata/xcschemes/FSNotes.xcscheme
FSNotes/Base.lproj/Main.storyboard
FSNotes/Business/LanguageType.swift
FSNotes/Preferences/PreferencesAdvancedViewController.swift
FSNotes/ja.lproj/Localizable.strings
FSNotes/ja.lproj/Main.strings

Added Japanese language support for FSNotes. Took care to ensure that the translation was consistent with Apple's official Japanese localization.
---
I've seen your tweet and couldn't help but donate money to the Ukrainian Embassy in Japan. I pray for your safety in this harsh situation🙏

Japanese support

---

FSNotes iOS/zh-Hans.lproj/InfoPlist.strings

Improve Chinese Simplified translations.

Create FSNotes iOS/zh-Hans.lproj/InfoPlist.strings

---

FSNotes iOS Share/zh-Hans-CN.lproj/Localizable.strings

Improve Chinese Simplified translations.

Update FSNotes iOS Share/zh-Hans-CN.lproj/Localizable.strings

---

FSNotes iOS/zh-Hans.lproj/Localizable.strings

This is the Chinese Simplified translation for iOS mobile.

Create FSNotes iOS/zh-Hans.lproj/Localizable.strings

---

FSNotes iOS/ViewController.swift

Updates table view according to current section.
fix for issue  #1533 
Fix video clip:
https://github.com/glushchenko/fsnotes/assets/32197474/e2ba9d82-1e1a-46ea-9c33-ec48f3ab3e42

Reload table w.r.t. current section

---

FSNotes iOS/zh-Hans.lproj/Localizable.strings

Improve some simplified Chinese translations.

Improve some simplified Chinese translations

---

README.md
README_zh_CN.md
README_zh_TW.md

I added Simplified and Traditional Chinese Translation.
Hope can be merged, thank you!

Added zh_CN & zh_TW README Translation

---

FSNotes iOS Share/Localizable.xcstrings
FSNotes iOS/Localizable.xcstrings
FSNotes.xcodeproj/project.pbxproj
FSNotes/Localizable.xcstrings

Czech GUI localization for Mac and iOS

Add Czech localization (cs)

---

FSNotes iOS/InfoPlist.xcstrings
FSNotes iOS/Localizable.xcstrings
FSNotes/AboutViewController.swift
FSNotes/Business/LanguageType.swift
FSNotes/mul.lproj/Main.xcstrings

Some files were missing in #1737 so here's the rest of the strings.
This time, I got around to actually building the app – which made me realize that the newly added language does not show up in the dropdown in "Advanced"?
Could you please check my changes to `FSNotes/Business/LanguageType.swift` and see if this is alright? Is there anything else needed?
Thanks!

Czech (cs): part 2

---

FSNotes iOS/Localizable.xcstrings
FSNotes/Localizable.xcstrings

It's only french localization. I have test it on iOS and macOS versions.

Update French localization
